apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kwok-with-vmi
rules:
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachineinstances
  verbs:
  - get
  - list
  - watch
  - delete
  - patch
  - update
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachineinstances/status
  verbs:
  - patch
  - update
- apiGroups:
  - kubevirt.io
  resources:
  - virtualmachineinstances/finalizers
  verbs:
  - patch
  - update
