apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: vmi-ready
spec:
  resourceRef:
    apiGroup: kubevirt.io/v1
    kind: VirtualMachineInstance
  selector:
    matchExpressions:
      - key: '.metadata.deletionTimestamp'
        operator: 'DoesNotExist'
      - key: '.status.phase'
        operator: 'NotIn'
        values:
        - 'Running'
      - key: '.spec.nodeSelector.type'
        operator: 'In'
        values:
        - 'kwok'
  next:
    statusTemplate: |
      {{ $now := Now }}
      phase: Running
      phaseTransitionTimestamps:
      - phase: Running
        phaseTransitionTimestamp: {{ $now }}
